---
# Tasks to deploy application artifacts

- name: Deploy tomcat application artifacts
  include_role:
    name: amtega.artifact
  vars:
    artifact_list: "{{ tomcat_artifacts_deployed }}"
    artifact_skip_packages: "{{ tomcat_application_skip_packages }}"
