---
# Tasks to setup application artifacts

- block:
    - block:
        - name: deploy tomcat application artifacts
          include_role:
            name: amtega.artifact
          vars:
            override:
              id: >-
                {{ "tomcat_application_"
                   + tomcat_application_name
                   + "_"
                   + tomcat_application_item.1.id }}
              dest: >-
                {{ tomcat_application_item.0.base
                   + "/"
                   + tomcat_application_item.1.dest }}
              owner: "{{ tomcat_application_item.0.user }}"
              group: "{{ tomcat_application_item.0.group }}"
            artifact: "{{ tomcat_application_item.1 | combine(override) }}"
          when: tomcat_application_state == "present"
          loop: >-
            {{ query('nested',
                     tomcat_application_server_instances,
                     tomcat_application_artifacts) }}
          loop_control:
            loop_var: tomcat_application_item
            label: >-
              {{ tomcat_application_item.0.base }}
              {{ tomcat_application_item.1.file }}

        - name: determining if it is necessary to restart the tomcat service
          command: /bin/true
          changed_when: artifact_result.changed
          loop: >-
            {{ query('nested',
                     tomcat_application_server_instances,
                     tomcat_application_artifacts) }}
          loop_control:
            loop_var: tomcat_application_item
            label: >-
              {{ tomcat_application_item.0.base }}
              {{ tomcat_application_item.1.file }}
          notify:
            - shutdown tomcat instance
          vars:
            artifact_result: >-
              {{ lookup('vars',
                        'artifact_result_tomcat_application_'
                        + tomcat_application_name
                        + '_'
                        + tomcat_application_item.1.id) }}
      when: tomcat_application_state == "present"

    - block:
        - name: remove tomcat application artifacts
          file:
            path: >-
              {{ tomcat_application_item.0.base
                 +"/"
                 + tomcat_application_item.1.dest
                 + "/"
                 + tomcat_application_item.1.file }}
            state: absent
          register: tomcat_application_undeploy_artifacts_result
          loop: >-
            {{ query('nested',
                     tomcat_application_server_instances,
                     tomcat_application_artifacts) }}
          loop_control:
            loop_var: tomcat_application_item
            label: >-
              {{ tomcat_application_item.0.base }}
              {{ tomcat_application_item.1.file }}
          notify:
            - shutdown tomcat instance

        - name: remove tomcat application deployed directories
          file:
            path: >-
              {{ tomcat_application_item.0.base
                 + "/"
                 + tomcat_application_item.1.dest
                 + "/"
                 + (tomcat_application_item.1.file | splitext).0 }}
            state: absent
          register: tomcat_application_undeploy_artifacts_dirs_result
          loop: >-
            {{ query('nested',
                     tomcat_application_server_instances,
                     tomcat_application_artifacts
                     | selectattr("file", "search", "\.war$")
                     | list) }}
          loop_control:
            loop_var: tomcat_application_item
            label: >-
              {{ tomcat_application_item.0.base }}
              (tomcat_application_item.1.file | splitext).0
          notify:
            - shutdown tomcat instance
      when: tomcat_application_state == "absent"
  tags:
    - role::tomcat_application
    - role::tomcat_application::artifacts
