---
# Tasks to setup application artifacts

- block:
    - name: Setup fact with application artifacts
      set_fact:
        tomcat_artifacts_deployed: >-
          {{ lookup('template', 'artifacts.yml.j2') | from_yaml }}

    - name: Deploy tomcat application artifacts
      include_role:
        name: amtega.artifact
      vars:
        artifact_list: "{{ tomcat_artifacts_deployed }}"
      when: tomcat_application_state == "present"

    - name: Determining if it is necessary to restart the tomcat service
      command: /bin/true
      changed_when:
        - artifact_result_item.changed
        - not tomcat_application_item.0.autodeploy
      loop: >-
        {{ query('nested',
                 tomcat_application_server_instances,
                 tomcat_application_artifacts) }}
      loop_control:
        loop_var: tomcat_application_item
        label: >-
          {{ tomcat_application_item.0.base }}
          {{ tomcat_application_item.1.file }}
      notify:
        - shutdown tomcat instance
      vars:
        artifact_result_item: >-
          {{ artifact_result["tomcat_application_"
                             + tomcat_application_name
                             + "_"
                             + tomcat_application_item.1.id] }}

    - block:
        - name: Remove tomcat application deployed directories
          file:
            path: >-
              {{ tomcat_application_item.0.base
                 + "/"
                 + tomcat_application_item.1.dest
                 + "/"
                 + (tomcat_application_item.1.file | splitext).0 }}
            state: absent
          register: tomcat_application_undeploy_artifacts_dirs_result
          loop: >-
            {{ query('nested',
                     tomcat_application_server_instances,
                     tomcat_application_artifacts
                     | selectattr("file", "search", "\.war$")
                     | list) }}
          loop_control:
            loop_var: tomcat_application_item
            label: >-
              {{ tomcat_application_item.0.base }}
              {{ (tomcat_application_item.1.file | splitext).0 }}
          notify:
            - shutdown tomcat instance
      when: tomcat_application_state == "absent"
  tags:
    - role::tomcat_application
    - role::tomcat_application::artifacts
