---
# Tasks to setup application artifacts

- block:
    - include_tasks: artifacts_fact.yml
    - include_tasks: artifacts_deploy.yml
    - include_tasks: artifacts_restart.yml

    - include_tasks: artifacts_remove.yml
      when: tomcat_application_state == "absent"
  tags:
    - role::tomcat_application
    - role::tomcat_application::artifacts
