---
# Role check tasks

- block:
    - name: verify role mandatory variables
      assert:
        that:
          - tomcat_application_name is defined
        msg: missing mandatory role variable

    - name: verify role mandatory variables
      assert:
        that:
          - item in server_instances_names
        msg: "application tomcat instance must be running in server"
      loop: "{{ tomcat_application_instances }}"
      vars:
        server_instances_names: >-
          {{ tomcat_application_server_instances
             | map(attribute="name")
             | list }}
  tags:
    - role::tomcat_application
    - role::tomcat_application::check
