---
# Tasks to setup application dirs
- block:
    - name: setup application datasources attributes
      xml:
        path: "{{ xml_path }}"
        xpath: >-
          {{ (not ds_attribute_to_remove)
             | ternary(ds_xpath_base,
                       ds_xpath_base
                       + "/@"
                       + ds_attribute) }}
        attribute: >-
          {{ (not ds_attribute_to_remove)
             | ternary(ds_attribute, omit) }}
        value: "{{ ds_attribute_value | string }}"
        state: >-
          {{ (not ds_attribute_to_remove)
             | ternary("present", "absent") }}
        pretty_print: true
      register: tomcat_application_setup_ds_result
      when: tomcat_application_state == "present"
      loop: >-
        {{ query('subelements',
                 lookup('template', 'datasources.yml.j2') | from_yaml,
                 'attributes_names') }}
      loop_control:
        label: "{{ item.0.name }} {{ item.1 }}"
      vars:
        ds_xpath_base: "/Context/Resource[@name='{{ item.0.name }}']"
        ds_attribute: "{{ item.1 }}"
        ds_attribute_value: "{{ item.0.attributes_values[item.1] }}"
        ds_attribute_to_remove: "{{ ds_attribute_value is none }}"

    - name: remove application datasources
      xml:
        path: "{{ xml_path }}"
        xpath: "/Context/Resource[@name='{{ item.name }}']"
        state: absent
        pretty_print: true
      when: tomcat_application_state == "absent"
      loop: "{{ tomcat_application_datasources }}"
      loop_control:
        label: "{{ item.name }}"
  vars:
    xml_path: >-
      {{ tomcat_application_server_instance.base
         + "/"
         + tomcat_application_context_config }}
  tags:
    - role::tomcat_application
    - role::tomcat_application::dirs
