---
# Tasks to setup application dirs

- block:
    - name: setup application datasources attributes
      xml:
        path: >-
          {{ tomcat_application_server_instance.base
             + "/"
             + tomcat_application_server_config }}
        xpath: >-
          {{ (not ds_attribute_to_remove)
             | ternary(ds_xpath_base,
                       ds_xpath_base
                       + "/@"
                       + ds_attribute) }}
        attribute: >-
          {{ (not ds_attribute_to_remove)
             | ternary(ds_attribute, omit) }}
        value: "{{ ds_attribute_value | string }}"
        state: >-
          {{ (not ds_attribute_to_remove)
             | ternary("present", "absent") }}
        pretty_print: true
      register: tomcat_application_setup_ds_result
      when: item.1 in item.0 or item.1 in ds_computed_attributes
      loop: >-
        {{ query('nested',
                 tomcat_application_datasources,
                 tomcat_application_datasource_attributes) }}
      loop_control:
        label: "{{ item.0.name }} {{ item.1 }}"
      vars:
        ds_xpath_base: >-
          /Server/GlobalNamingResources/Resource[@name='{{ item.0.name }}']
        ds_attribute: >-
          {{ tomcat_application_datasource_attributes[item.1] }}
        ds_attribute_value: >-
          {{ item.0[item.1]
             | default(ds_computed_attributes[item.1]) }}
        ds_attribute_to_remove: >-
          {{ item.0[item.1] is none }}
        ds_cache_properties_strings:
          - >-
            {{ (item.0.connection_cache_min_limit is defined)
               | ternary("MinLimit=" + item.0.connection_cache_min_limit
                         | string,
                         "") }}
          - >-
            {{ (item.0.connection_cache_max_limit is defined)
               | ternary("MinLimit=" + item.0.connection_cache_max_limit
                         | string,
                         "") }}
          - >-
            {{ (item.0.connection_cache_initial_limit is defined)
               | ternary("MinLimit=" + item.0.connection_cache_initial_limit
                         | string,
                         "") }}
        ds_cache_properties: >-
          {{ '{' + ds_cache_properties_strings | join(',') + '}' }}
        ds_computed_attributes:
          connection_cache_properties: "{{ ds_cache_properties }}"
  tags:
    - role::tomcat_application
    - role::tomcat_application::dirs
