---
# Tasks to setup application dirs

- block:
    - name: apply templates to data sources
      set_fact:
        tomcat_application_datasources_templated: >-
          {{ tomcat_application_datasources_templated | default([])
             + lookup("template", "template_ds.yml.j2") | from_yaml }}
      loop: "{{ tomcat_application_datasources }}"
      loop_control:
        loop_var: tomcat_application_datasource
        index_var: tomcat_application_datasource_index
        label: "{{ tomcat_application_datasource_index }}"

    - debug: var=tomcat_application_datasources_templated

    - fail:

    - name: setup application datasources attributes
      xml:
        path: "{{ ds_path }}"
        xpath: >-
          {{ (not ds_attribute_to_remove)
             | ternary(ds_xpath_base,
                       ds_xpath_base
                       + "/@"
                       + ds_attribute) }}
        attribute: >-
          {{ (not ds_attribute_to_remove)
             | ternary(ds_attribute, omit) }}
        value: "{{ ds_attribute_value | string }}"
        state: >-
          {{ (not ds_attribute_to_remove)
             | ternary("present", "absent") }}
        pretty_print: true
      register: tomcat_application_setup_ds_result
      when: tomcat_application_state == "present"
      loop: >-
        {{ query('subelements',
                 lookup('template', 'datasources.yml.j2') | from_yaml,
                 'attributes_names') }}
      loop_control:
        label: "{{ ds_path }} {{ item.0.name }} {{ item.1 }}"
      notify:
        - shutdown tomcat instance
      vars:
        ds_path: "{{ item.0.base }}/{{ tomcat_application_context_config }}"
        ds_xpath_base: "/Context/Resource[@name='{{ item.0.name }}']"
        ds_attribute: "{{ item.1 }}"
        ds_attribute_value: "{{ item.0.attributes_values[item.1] }}"
        ds_attribute_to_remove: "{{ ds_attribute_value is none }}"

    - name: remove application datasources
      xml:
        path: "{{ item.0.base }}/{{ tomcat_application_context_config }}"
        xpath: "/Context/Resource[@name='{{ item.1.name }}']"
        state: absent
        pretty_print: true
      when: tomcat_application_state == "absent"
      register: tomcat_application_remove_ds_result
      loop: >-
        {{ query('nested',
                 tomcat_application_server_instances,
                 tomcat_application_datasources) }}
      loop_control:
        label: "{{ item.1.name }}"
      notify:
        - shutdown tomcat instance
  tags:
    - role::tomcat_application
    - role::tomcat_application::datasources
