---
# Tasks to setup application dirs

- block:
    - name: Setup fact with templated datasources
      set_fact:
        tomcat_application_datasources_deployed: >-
          {{ tomcat_application_datasources_deployed | default([])
             + lookup("template", "datasources_templated.yml.j2") | from_yaml }}
      loop: "{{ tomcat_application_datasources }}"
      loop_control:
        loop_var: tomcat_application_datasource
        index_var: tomcat_application_datasource_index
        label: "{{ tomcat_application_datasource_index }}"
      vars:
        tomcat_application_datasource_index0: >-
          {{ tomcat_application_datasource_index }}
        tomcat_application_datasource_index1: >-
          {{ tomcat_application_datasource_index + 1 }}

    - name: Setup application datasources attributes
      xml:
        path: "{{ ds_path }}"
        xpath: >-
          {{ (not ds_attribute_to_remove)
             | ternary(ds_xpath_base,
                       ds_xpath_base
                       + "/@"
                       + ds_attribute) }}
        attribute: >-
          {{ (not ds_attribute_to_remove)
             | ternary(ds_attribute, omit) }}
        value: "{{ ds_attribute_value | string }}"
        state: >-
          {{ (not ds_attribute_to_remove)
             | ternary("present", "absent") }}
        pretty_print: true
      register: tomcat_application_setup_ds_result
      when: tomcat_application_state == "present"
      loop: >-
        {{ query('subelements',
                 lookup('template', 'datasources.yml.j2') | from_yaml,
                 'attributes_names') }}
      loop_control:
        loop_var: tomcat_application_item
        label: >-
          {{ ds_path }}
          {{ tomcat_application_item.0.name }}
          {{ tomcat_application_item.1 }}
      notify:
        - shutdown tomcat instance
      vars:
        ds_path: >-
          {{ tomcat_application_item.0.base
             + "/"
             + tomcat_application_context_config }}
        ds_xpath_base: >-
          /Context/Resource[@name='{{ tomcat_application_item.0.name }}']
        ds_attribute: "{{ tomcat_application_item.1 }}"
        ds_attribute_all_values: >-
          {{ tomcat_application_item.0.attributes_values }}
        ds_attribute_value: >-
          {{ ds_attribute_all_values[tomcat_application_item.1] }}
        ds_attribute_to_remove: "{{ ds_attribute_value is none }}"

    - name: Remove application datasources
      xml:
        path: >-
          {{ tomcat_application_item.0.base
             + "/"
             + tomcat_application_context_config }}
        xpath: "/Context/Resource[@name='{{ tomcat_application_item.1.name }}']"
        state: absent
        pretty_print: true
      when: tomcat_application_state == "absent"
      register: tomcat_application_remove_ds_result
      loop: >-
        {{ query('nested',
                 tomcat_application_server_instances,
                 tomcat_application_datasources_deployed) }}
      loop_control:
        loop_var: tomcat_application_item
        label: "{{ tomcat_application_item.1.name }}"
      notify:
        - shutdown tomcat instance
  tags:
    - role::tomcat_application
    - role::tomcat_application::datasources
