---
# Tasks to setup application dirs

- block:
    - name: setup application directories
      file:
        path: "{{ item.0.base }}/{{ item.1 }}"
        state: directory
        owner: "{{ item.0.user }}"
        group: "{{ item.0.group }}"
        mode: 0755
      when: tomcat_application_state == "present"
      loop: >-
        {{ query('nested',
                 tomcat_application_server_instances,
                 tomcat_application_dirs) }}
      loop_control:
        label: "{{ item.0.base }}/{{ item.1 }}"

    - name: remove application directories
      file:
        path: "{{ item.0.base }}/{{ item.1 }}"
        state: absent
      when:
        - tomcat_application_state == "absent"
        - tomcat_application_dirs_remove
      loop: >-
        {{ query('nested',
                 tomcat_application_server_instances,
                 tomcat_application_dirs) }}
      loop_control:
        label: "{{ item.0.base }}/{{ item.1 }}"
  tags:
    - role::tomcat_application
    - role::tomcat_application::dirs
