---
# Tasks to setup application dirs

- block:
    - name: setup application directories
      file:
        path: "{{ instance.base }}/{{ directory }}"
        state: directory
        owner: "{{ instance.user }}"
        group: "{{ instance.group }}"
        mode: 0755
      loop: "{{ tomcat_application_dirs }}"
      loop_control:
        loop_var: directory
      vars:
        instance: >-
          {{ tomcat_application_server_instances[tomcat_application_instance] }}
  tags:
    - role::tomcat_application
    - role::tomcat_application::dirs
