---
# Tasks to setup application dirs

- block:
    - name: Setup application directories
      file:
        path: >-
          {{ tomcat_application_item.0.base }}/{{ tomcat_application_item.1 }}
        state: directory
        owner: "{{ tomcat_application_item.0.user }}"
        group: "{{ tomcat_application_item.0.group }}"
        mode: "0755"
      when: tomcat_application_state == "present"
      loop: >-
        {{ query('nested',
                 tomcat_application_server_instances,
                 tomcat_application_dirs) }}
      loop_control:
        loop_var: tomcat_application_item
        label: >-
          {{ tomcat_application_item.0.base }}/{{ tomcat_application_item.1 }}

    - name: Remove application directories
      file:
        path: >-
          {{ tomcat_application_item.0.base }}/{{ tomcat_application_item.1 }}
        state: absent
      when:
        - tomcat_application_state == "absent"
        - tomcat_application_dirs_remove | bool
      loop: >-
        {{ query('nested',
                 tomcat_application_server_instances,
                 tomcat_application_dirs) }}
      loop_control:
        loop_var: tomcat_application_item
        label: >-
          {{ tomcat_application_item.0.base }}/{{ tomcat_application_item.1 }}
      ignore_errors: "{{ tomcat_application_dirs_remove_ignore_errors }}"
  tags:
    - role::tomcat_application
    - role::tomcat_application::directories
