---
# Role tasks

- name: gather tomcat instances facts
  import_tasks: facts.yml
  tags:
    - role::tomcat_application

- name: sanity checks
  import_tasks: check.yml
  tags:
    - role::tomcat_application
    - role::tomtomcat_applicationcat::check

- name: setup application directories
  import_tasks: directories.yml
  tags:
    - role::tomcat_application
    - role::tomcat_application::directories

- name: setup application datasources
  import_tasks: datasources.yml
  tags:
    - role::tomcat_application
    - role::tomcat_application::datasources
