---
# Role tasks

- name: gather tomcat instances facts
  include_tasks: facts.yml
  tags:
    - role::tomcat_application
    - role::tomcat_application::facts

- name: sanity checks
  include_tasks: check.yml
  tags:
    - role::tomcat_application
    - role::tomcat_application::check

- name: setup application directories
  include_tasks: directories.yml
  when:
    - tomcat_application_dirs is defined
    - tomcat_application_dirs is not none
    - tomcat_application_dirs | length > 0
  tags:
    - role::tomcat_application
    - role::tomcat_application::directories

- name: setup application datasources
  include_tasks: datasources.yml
  when:
    - tomcat_application_datasources is defined
    - tomcat_application_datasources is not none
    - tomcat_application_datasources | length > 0
  tags:
    - role::tomcat_application
    - role::tomcat_application::datasources

- name: setup application artifacts
  include_tasks: artifacts.yml
  tags:
    - role::tomcat_application
    - role::tomcat_application::artifacts

- name: verify deployment
  include_tasks: verify.yml
  tags:
    - role::tomcat_application
    - role::tomcat_application::verify
