---
# Role tasks

- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 6
      fedora: 27
      rhel: 6
    check_platform_variables:
      - tomcat_application_name

- include_role:
    name: amtega.packages
  vars:
    packages_os:
      centos:
        6:
          python-lxml: absent
        7:
          python-lxml: present
      fedora:
        all:
          python2-lxml: present
          python3-lxml: present
      rhel:
        6:
          python-lxml: abbsent
        7:
          python-lxml: present
    packages_python:
      centos:
        6:
          lxml==4.2.6: present
      rhel:
        6:
          lxml==4.2.6: present

- name: Gather tomcat instances facts
  include_tasks: facts.yml
  tags:
    - role::tomcat_application
    - role::tomcat_application::facts

- name: Sanity checks
  include_tasks: check.yml
  tags:
    - role::tomcat_application
    - role::tomcat_application::check

- name: Setup application directories
  include_tasks: directories.yml
  when:
    - tomcat_application_dirs is defined
    - tomcat_application_dirs is not none
    - tomcat_application_dirs | length > 0
  tags:
    - role::tomcat_application
    - role::tomcat_application::directories

- name: Setup application datasources
  include_tasks: datasources.yml
  when:
    - tomcat_application_datasources is defined
    - tomcat_application_datasources is not none
    - tomcat_application_datasources | length > 0
  tags:
    - role::tomcat_application
    - role::tomcat_application::datasources

- name: Setup application artifacts
  include_tasks: artifacts.yml
  tags:
    - role::tomcat_application
    - role::tomcat_application::artifacts

- name: Verify deployment
  include_tasks: verify.yml
  tags:
    - role::tomcat_application
    - role::tomcat_application::verify
