---
# Role verify tasks

- block:
    - name: verify that application was deployed correctly
      uri:
        url: "{{ tomcat_application_manager.0.url }}/manager/text/list"
        method: GET
        user: "{{ tomcat_application_manager.0.user | default(omit )}}"
        password: "{{ tomcat_application_manager.0.password | default(omit) }}"
        return_content: yes
        timeout: "{{ tomcat_application_manager.0.timeout | default(3) }}"
      register: tomcat_application_manager_result
      retries: "{{ tomcat_application_manager.0.retries | default(0) }}"
      delay: "{{ tomcat_application_manager.0.delay | default(0) }}"
      until: >-
        tomcat_application_manager_result.content
        is search("/" + tomcat_application_name + ":running")
      when: tomcat_application_manager | length > 0
      no_log: "{{ tomcat_application_no_log }}"
      loop: "{{ tomcat_application_instances }}"
      loop_control:
        loop_var: tomcat_application_instance
        label: "{{ tomcat_application_instance }}"
      vars:
        tomcat_application_manager: >-
          {{ tomcat_application_managers
             | selectattr("instance", "equalto", tomcat_application_instance)
             | list }}
  tags:
    - role::tomcat_application
    - role::tomcat_application::verify
