---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  export ANSIBLE_ACTION_PLUGINS=$PWD/action_plugins
  export ANSIBLE_BECOME_PLUGINS=$PWD/become_plugins
  export ANSIBLE_CACHE_PLUGINS=$PWD/cache_plugins
  export ANSIBLE_CALLBACK_PLUGINS=$PWD/callback_plugins
  export ANSIBLE_CLICONF_PLUGINS=$PWD/cliconf_plugins
  export ANSIBLE_CONNECTION_PLUGINS=$PWD/connection_plugins
  export ANSIBLE_DOC_FRAGMENT_PLUGINS=$PWD/doc_fragment_plugins
  export ANSIBLE_FILTER_PLUGINS=$PWD/filter_plugins
  export ANSIBLE_HTTPAPI_PLUGINS=$PWD/httpapi_plugins
  export ANSIBLE_INVENTORY_PLUGINS=$PWD/inventory_plugins
  export ANSIBLE_LIBRARY=$PWD/library
  export ANSIBLE_LOOKUP_PLUGINS=$PWD/lookup_plugins
  export ANSIBLE_NETCONF_PLUGINS=$PWD/netconf_plugins
  export ANSIBLE_STRATEGY_PLUGINS=$PWD/strategy_plugins
  export ANSIBLE_TERMINAL_PLUGINS=$PWD/terminal_plugins
  export ANSIBLE_TEST_PLUGINS=$PWD/test_plugins
  export ANSIBLE_VARS_PLUGINS=$PWD/vars_plugins
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "fedora29-${INSTANCE_UUID:-1}"
    image: fedora:29
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_29
  - name: "fedora30-${INSTANCE_UUID:-1}"
    image: fedora:30
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_30
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    group_vars:
      molecule_hosts:
        tomcat_application_name: sample
        tomcat_application_instances:
          - tomcat@server1
          - tomcat@server2
        tomcat_application_artifacts:
          - id: sample_war
            type: https
            host: https://tomcat.apache.org
            path: /tomcat-8.0-doc/appdev/sample
            file: sample.war
            dest: webapps
            timeout: 120
            validate_certs: no
          - id: release_notes
            type: https
            host: https://archive.apache.org
            path: /dist/tomcat/tomcat-8/v8.0.1
            file: RELEASE-NOTES
            dest: logs
            timeout: 120
            validate_certs: no
          - id: sample2_war
            type: http
            host: "file:"
            path: /tmp
            file: sample2.war
            dest: webapps
            timeout: 120
        tomcat_application_dirs:
          - "config/{{ tomcat_application_name }}"
          - "log/{{ tomcat_application_name }}"
          - "cert/{{ tomcat_application_name }}"
          - "data/{{ tomcat_application_name }}"
          - "resource/{{ tomcat_application_name }}"
        tomcat_application_datasources:
          - name: "jdbc/{{ tomcat_application_name }}DS01"
            auth: Container
            type: acme.jdbc.pool.AcmeDataSource
            factory: acme.jdbc.pool.AcmeDataSourceFactory
            driverClassName: acme.jdbc.AcmeDriver
            maxTotal: 100
            maxIdle: 30
            maxWaitMilli: 10000
            url: dbc:acme:@DATABASE
            user: app
            password: app_password
          - name: "jdbc/{{ tomcat_application_name }}DS02"
            auth: Container
            type: acme.jdbc.pool.AcmeDataSource
            factory: acme.jdbc.pool.AcmeDataSourceFactory
            driverClassName: acme.jdbc.AcmeDriver
            maxTotal: 100
            maxIdle: 30
            maxWaitMilli: 10000
            url: dbc:acme:@DATABASE
            user: app
            password: app_password
        tomcat_application_state: absent
        tomcat_application_dirs_remove: true
verifier:
  name: ansible
