---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - meta: flush_handlers

    - name: Search application dirs
      stat:
        path: "{{ item.0.base }}/{{ item.1 }}"
      loop: >-
        {{ query('nested',
                 tomcat_application_server_instances,
                 tomcat_application_dirs) }}
      register: check_application_dirs_result
      loop_control:
        label: "{{ item.0.base }}/{{ item.1 }}"

    - name: Check application dirs does not exist
      assert:
        that: not item
      loop: >-
        {{ check_application_dirs_result.results
           | map(attribute='stat.exists')
           | list }}

    - name: Check datasources config
      xml:
        path: "{{ item.0.base }}/conf/context.xml"
        xpath: "/Context/Resource[@name='{{ item.1.name }}']"
        content: attribute
      register: ds
      failed_when: ds.matches is defined
      loop: >-
        {{ query('nested',
                 tomcat_application_server_instances,
                 tomcat_application_datasources_deployed) }}
      loop_control:
        label: "{{ item.0.name }} {{ item.1.name }}"

    - name: Search application artifacts
      stat:
        path: "{{ item }}"
      loop:
        - /srv/tomcat/tomcat@server1/webapps/sample.war
        - /srv/tomcat/tomcat@server1/webapps/sample2.war
        - /srv/tomcat/tomcat@server1/webapps/sample
        - /srv/tomcat/tomcat@server1/webapps/sample2
        - /srv/tomcat/tomcat@server2/webapps/sample.war
        - /srv/tomcat/tomcat@server2/webapps/sample2.war
        - /srv/tomcat/tomcat@server2/webapps/sample
        - /srv/tomcat/tomcat@server2/webapps/sample2
      register: check_application_artifacts_result

    - name: Check application artifacts does not exist
      assert:
        that: not item
      loop: >-
        {{ check_application_artifacts_result.results
           | map(attribute='stat.exists')
           | list }}

    - name: Check application is not working
      uri:
        url: "{{ item }}"
        return_content: yes
      register: check_application_result
      failed_when: >-
        check_application_result.content
             is search("Sample.*Hello.*World.*Application")
      loop:
        - http://localhost:8080/sample
        - http://localhost:8080/sample2
        - http://localhost:8081/sample
        - http://localhost:8081/sample2

  vars:
    tomcat_application_server_instances:
      - name: tomcat@server1
        base: /srv/tomcat/tomcat@server1
      - name: tomcat@server2
        base: /srv/tomcat/tomcat@server2

    tomcat_application_datasources_deployed: >-
      {{ tomcat_application_datasources }}
