---
# Handlers to restart tomcat instance

- block:
    - name: Tomcat_application restart tomcat instances using os services
      service:
        name: "{{ tomcat_application_instance.name }}"
        state: restarted
      loop: >-
        {{ tomcat_application_server_instances
           | selectattr("service", "equalto", true)
           | list }}
      loop_control:
        loop_var: tomcat_application_instance
        label: "{{ tomcat_application_instance.name }}"
      listen:
        - shutdown tomcat instance
        - start tomcat instance

    - name: Tomcat_application shutdown tomcat instance using custom scripts
      shell: >-
        {{ tomcat_application_instance.base
           + "/"
           + tomcat_application_instance_shutdown
             | default(default_shutdown) }} ;
        sleep {{ tomcat_application_instance_restart_pause }}
      args:
        warn: no
      when:
        - tomcat_application_instance_shutdown is defined
        - tomcat_application_instance_shutdown is not none
        - tomcat_application_instance_shutdown | length > 0
      loop: >-
        {{ tomcat_application_server_instances
           | selectattr("service", "equalto", false)
           | list }}
      loop_control:
        loop_var: tomcat_application_instance
        label: "{{ tomcat_application_instance.name }}"
      notify:
        - start tomcat instance
      become: yes
      become_user: "{{ tomcat_application_instance.user }}"
      become_method: "{{ tomcat_application_instance_restart_become_method }}"
      listen: shutdown tomcat instance

      # To start we have to consider that eventually the process could have
      # been restart againg by underlying software as systemd. So, we accept as
      # valid return state !=0 if the process is running

    - name: Tomcat_application start tomcat instance using custom scripts
      command: >-
        {{ tomcat_application_instance.base
           + "/"
           + tomcat_application_instance_startup
             | default(default_startup) }}
      register: tomcat_application_start_instance_result
      failed_when: >-
        tomcat_application_start_instance_result.rc != 0
        and not tomcat_application_start_instance_result.stdout
                is search("Tomcat appears to still be running")
      when:
        - tomcat_application_instance_startup is defined
        - tomcat_application_instance_startup is not none
        - tomcat_application_instance_startup | length > 0
      loop: >-
        {{ tomcat_application_server_instances
           | selectattr("service", "equalto", false)
           | list }}
      loop_control:
        loop_var: tomcat_application_instance
        label: "{{ tomcat_application_instance.name }}"
      become: yes
      become_user: "{{ tomcat_application_instance.user }}"
      become_method: "{{ tomcat_application_instance_restart_become_method }}"
      listen: start tomcat instance

  when: >-
    (not tomcat_application_instance.autodeploy
     and (artifacts_changed or undeploy_changed))
    or ds_setup_changed
  vars:
    artifacts_changed: >-
      {{ (artifact_result | default({})).values()
         | selectattr("changed", "defined")
         | selectattr("changed", "equalto", True)
         | list
         | length > 0 }}

    undeploy_changed: >-
      {{ ((tomcat_application_undeploy_artifacts_result
           | default({"results": []})).results
          + (tomcat_application_undeploy_artifacts_dirs_result
             | default({"results": []})).results)
         | selectattr("changed", "defined")
         | select("changed")
         | selectattr("tomcat_application_item.0.base",
                      "equalto",
                      tomcat_application_instance.base)
         | list
         | length > 0 }}

    ds_setup_changed: >-
      {{ ((tomcat_application_setup_ds_result
           | default({"results": []})).results
          + (tomcat_application_remove_ds_result
             | default({'results': []})).results)
         | selectattr("changed", "defined")
         | select("changed")
         | selectattr("tomcat_application_item.0.base",
                      "equalto",
                      tomcat_application_instance.base)
         | list
         | length > 0 }}

    default_startup: >-
      {{ (tomcat_application_instance.jsvc)
         | ternary("bin/daemon.sh start", "bin/startup.sh") }}
    default_shutdown: >-
      {{ (tomcat_application_instance.jsvc)
         | ternary("bin/daemon.sh stop", "bin/shutdown.sh") }}
  tags:
    - role::tomcat_application
    - role::tomcat_application::instance
