---
# Handlers to restart tomcat instance

- block:
    - name: tomcat_application shutdown tomcat instance
      shell: >-
        {{ instance.base }}/{{ tomcat_application_instance_shutdown }} ;
        sleep {{ tomcat_application_instance_restart_pause }}
      register: result1
      loop: "{{ tomcat_application_server_instances }}"
      loop_control:
        loop_var: instance
        label: "{{ instance.name }}"
      notify:
        - start tomcat instance
      listen: shutdown tomcat instance
      become: yes
      become_user: "{{ instance.user }}"
      become_method: "{{ tomcat_application_instance_restart_become_method }}"

    - name: tomcat_application start tomcat instance
      shell: "{{ instance.base }}/{{ tomcat_application_instance_startup }}"
      register: result
      loop: "{{ tomcat_application_server_instances }}"
      loop_control:
        loop_var: instance
        label: "{{ instance.name }}"
      listen: start tomcat instance
      become: yes
      become_user: "{{ instance.user }}"
      become_method: "{{ tomcat_application_instance_restart_become_method }}"
  when: >-
    (not instance.autodeploy
     and (tomcat_application_deploy_result.results
          + tomcat_application_undeploy_artifacts_result.results
          + tomcat_application_undeploy_artifacts_dirs_result.results)
         | select('changed')
         | selectattr("item.0.base", "equalto", instance.base)
         | list
         | length > 0)
    or (tomcat_application_setup_ds_result.results
        + tomcat_application_remove_ds_result.results)
       | select('changed')
       | selectattr("item.0.base", "equalto", instance.base)
       | list
       | length > 0
  tags:
    - role::tomcat_application
    - role::tomcat_application::instance
